# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch
import torch

# Create random tensor
random_tensor_a = torch.rand(7,7)
random_tensor_a

tensor([[0.8429, 0.6226, 0.0956, 0.8474, 0.0380, 0.9497, 0.0203],
        [0.2001, 0.9891, 0.6048, 0.8109, 0.2347, 0.6307, 0.1790],
        [0.1810, 0.5846, 0.3165, 0.6128, 0.5454, 0.8043, 0.6783],
        [0.1632, 0.9051, 0.3170, 0.6678, 0.7080, 0.9457, 0.8194],
        [0.0951, 0.4889, 0.8249, 0.9097, 0.9959, 0.6337, 0.0835],
        [0.6279, 0.3896, 0.5912, 0.1311, 0.2114, 0.1471, 0.4842],
        [0.6192, 0.9700, 0.8061, 0.6331, 0.2124, 0.8364, 0.1696]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [5]:
# Create another random tensor
random_tensor_b = torch.rand(1,7)
# Perform matrix multiplication 
torch.mm(random_tensor_a,random_tensor_b.T)

tensor([[1.6897],
        [2.3529],
        [2.3666],
        [2.9655],
        [2.6784],
        [1.4354],
        [2.4058]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [8]:
# Set manual seed
random_seed = 0
torch.manual_seed(random_seed)
# Create two random tensors
random_tensor_c = torch.rand(7,7)
random_tensor_d = torch.rand(1,7)
# Matrix multiply tensors
matrix_multiplication = torch.mm(random_tensor_c,random_tensor_d.T)
matrix_multiplication, matrix_multiplication.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [9]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [23]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")
# Create two random tensors on GPU
tensor_A = torch.rand(2,3).to(device)
tensor_B = torch.rand(2,3).to(device)
tensor_A,tensor_B

Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [25]:
# Perform matmul on tensor_A and tensor_B
matmul = torch.mm(tensor_A,tensor_B.T)
matmul, matmul.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [27]:
# Find max
max = torch.max(matmul)
# Find min
min = torch.min(matmul)
min,max

(tensor(0.3647, device='cuda:0'), tensor(0.5617, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [29]:
# Find arg max
arg_max = torch.argmax(matmul)

# Find arg min
arg_min = torch.argmin(matmul)
arg_min,arg_max

(tensor(0, device='cuda:0'), tensor(3, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [33]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_C = torch.rand([1,1,1,10])

# Remove single dimensions
tensor_D = tensor_C.squeeze()

# Print out tensors and their shapes
print(tensor_C, tensor_C.shape)
print(tensor_D, tensor_D.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
