In [145]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.1+cu118


In [146]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [147]:
scalar.ndim

0

In [148]:
scalar.item()

7

In [149]:
vector= torch.tensor([7,7,7,7])
vector

tensor([7, 7, 7, 7])

In [150]:
vector.ndim


1

In [151]:
vector.shape

torch.Size([4])

In [152]:
matrix = torch.tensor([[7,7], [8,1]])
matrix

tensor([[7, 7],
        [8, 1]])

In [153]:
tensor = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [154]:
tensor.ndim

3

In [155]:
tensor.shape

torch.Size([1, 3, 3])

In [156]:
tensor.ndim

3

In [157]:
tensor = torch.tensor([[[3,2,1],[3,2,1],[32,1,32]],[[123,321,123],[6,4,2],[80,12,20]]])
tensor

tensor([[[  3,   2,   1],
         [  3,   2,   1],
         [ 32,   1,  32]],

        [[123, 321, 123],
         [  6,   4,   2],
         [ 80,  12,  20]]])

In [158]:
tensor.shape

torch.Size([2, 3, 3])

In [159]:
tensor.ndim

3

In [160]:
tensor.size()

torch.Size([2, 3, 3])

In [161]:
tensor.device

device(type='cpu')

In [162]:
#Random tensor
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

In [163]:
random_image = torch.rand(size = (224, 224, 3)) #height, width, color channels (rgb)
random_image.shape, random_image.ndim

(torch.Size([224, 224, 3]), 3)

In [164]:
#zero/one tensor
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [165]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [166]:
#range of tensors and tensors-like
torch.range(0,10)

C:\Users\appclan\AppData\Local\Temp\ipykernel_5956\2533155496.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [167]:
one_to_hundred = torch.arange(start=0, end = 100, step= 10)
one_to_hundred

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [168]:
ten_zeros = torch.zeros_like(input=one_to_hundred)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [169]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                                dtype= None, # data type
                                device = None, # which device use tensor
                                requires_grad=False) #track gradients
float_32_tensor

tensor([3., 6., 9.])

In [170]:
float_16_tensor = float_32_tensor.type(torch.float16) # or half
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [171]:
(float_16_tensor * float_32_tensor).dtype
#float_16_tensor.dtype, float_32_tensor.dtype

torch.float32

In [172]:
int_32_tensor = torch.tensor([3,6,9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [173]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

#get info from tensors
1. Tensor datatype = tensor.dtype
2. Tensor shape = tensor.shape
3. Tensor device = tensor.device

In [174]:
some_tensor = torch.rand(3,4,4).type(torch.float16).to(device="cpu")
some_tensor

tensor([[[0.5747, 0.9199, 0.3230, 0.8613],
         [0.0919, 0.3103, 0.9536, 0.6001],
         [0.0351, 0.6826, 0.3743, 0.5220],
         [0.1335, 0.9668, 0.9756, 0.8477]],

        [[0.8989, 0.1105, 0.4563, 0.9722],
         [0.3967, 0.1495, 0.4744, 0.9976],
         [0.4436, 0.9727, 0.5195, 0.5337],
         [0.7051, 0.3362, 0.7891, 0.1693]],

        [[0.1801, 0.7178, 0.6987, 0.5508],
         [0.2485, 0.8516, 0.0963, 0.1338],
         [0.2742, 0.6143, 0.8975, 0.3628],
         [0.1748, 0.2401, 0.5459, 0.7305]]], dtype=torch.float16)

In [175]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[[0.5747, 0.9199, 0.3230, 0.8613],
         [0.0919, 0.3103, 0.9536, 0.6001],
         [0.0351, 0.6826, 0.3743, 0.5220],
         [0.1335, 0.9668, 0.9756, 0.8477]],

        [[0.8989, 0.1105, 0.4563, 0.9722],
         [0.3967, 0.1495, 0.4744, 0.9976],
         [0.4436, 0.9727, 0.5195, 0.5337],
         [0.7051, 0.3362, 0.7891, 0.1693]],

        [[0.1801, 0.7178, 0.6987, 0.5508],
         [0.2485, 0.8516, 0.0963, 0.1338],
         [0.2742, 0.6143, 0.8975, 0.3628],
         [0.1748, 0.2401, 0.5459, 0.7305]]], dtype=torch.float16)
Datatype of tensor: torch.float16
Shape of tensor: torch.Size([3, 4, 4])
Device tensor is on: cpu


### manipulating tensors

* add
* sub
* mult (element-wise)
* div
* mat_mult

In [176]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [177]:
tensor * 10

tensor([10, 20, 30])

In [178]:
tensor - 10

tensor([-9, -8, -7])

In [179]:
#Inbuilt func
torch.mul(tensor,10)

tensor([10, 20, 30])

###matrix mult
1. element-wise mult
2. matrix mult (dot product)

In [180]:
tensor

tensor([1, 2, 3])

In [181]:
print(tensor, "*" ,tensor)
print(f"Equals : {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals : tensor([1, 4, 9])


In [182]:
torch.matmul(tensor,tensor)

tensor(14)

In [183]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 2.99 ms


In [184]:
%%time
torch.matmul(tensor,tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

### Main rules for matrix_mult:
1. inner dimensions must match:
    * (3,1) @ (1,3)
2. result shape = outer dimensions:
    * (3,1) @ (1,3) = (3,3)


In [185]:
print(torch.rand(3,1) @ torch.rand(1,3))

tensor([[0.2111, 0.1523, 0.5256],
        [0.2683, 0.1936, 0.6679],
        [0.1288, 0.0929, 0.3206]])


### shape error

In [187]:
#shape for mat_mult
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
torch.mm(tensor_A, tensor_B) # mm = mat_mult

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [104]:
#to fix, use on one tensor transpose func
tensor_B.T, tensor_B.T.shape

In [106]:
torch.mm(tensor_A, tensor_B.T)

In [107]:
torch.mm(tensor_A.T, tensor_B)

 ### min max mean sum, etc (aggregate)

In [51]:
x = torch.arange(0,100,10)
x, x.dtype

In [48]:
torch.min(x) ,x.min()

In [49]:
torch.max(x), x.max()

In [50]:
torch.mean(x)

In [53]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

In [54]:
torch.sum(x), x.sum()

### index of max/min

In [58]:
x

In [61]:
x.argmax(), x[9]

In [62]:
torch.argmin(x), x[0]

### reshape, stack, squeeze, unsqueeze
* reshape - reshapes and input tensor to a defined shape
* view - return a view of an input tensor, having the same memory as input tensor
* stack - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* squeeze - remove all '1' dimensions
* unsqueeze - add a '1' dimension
* permute - return a view of the input with dimensions permuted(swapped)

In [64]:
x = torch.arange(1.,10.)
x, x.shape

In [65]:
x_reshaped = x.reshape(1,7)

In [66]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

In [67]:
x.reshape(9,1)

In [68]:
x.reshape(3,3)

In [69]:
z = x.view(1,9)
z, z.shape

In [71]:
#changing view (z) changes x 
z[:,0] = 5
z, x

In [75]:
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

In [78]:
x_vstacked = torch.vstack([x,x,x,x])
x_vstacked

In [84]:
x_hstacked = torch.hstack([x,x,x,x])
x_hstacked

In [97]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

In [100]:
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

x_unsquezeed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsquezeed}")
print(f"New shape: {x_unsquezeed.shape}")

In [115]:
x_original = torch.rand(size=(224,224,3)) #height, width, color_channels
#permute - rearrenge the axis (dims) order
x_permuted = x_original.permute(2,0,1) # 0->1, 1->2, 2->0
print(f"Previous shape: {x_original.shape}")
print(f"New sahpe: {x_permuted.shape}")


### Indexing 

In [118]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

In [119]:
x[0]

In [121]:
x[0,0], x[0][0]

In [124]:
x[0][0][0], x[0][2][2]

In [125]:
x[:, 0]

In [127]:
x[:,:,1]

In [128]:
x[:,:,2]

### Pytorch tensors & NumPy
* Data in np to tensor = `torch.from_numpy(ndarray)`
* tensor to numpy array = `torch.Tensor.numpy()`

In [130]:
array = np.arange(1.,8.) #dtype = float64
tensor = torch.from_numpy(array)
array, tensor

In [131]:
array = array + 1
array, tensor

In [132]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

In [133]:
tensor = tensor + 1
tensor, numpy_tensor

In [134]:
rand_tensor_A = torch.rand(3,4)
rand_tensor_B = torch.rand(3,4)
rand_tensor_A, rand_tensor_B

In [136]:
random_seed = 42
torch.manual_seed(random_seed)
random_tensor_C = torch.rand(3,4)
torch.manual_seed(random_seed)
random_tensor_D = torch.rand(3,4)
random_tensor_C, random_tensor_D

### Running pytorch objects on GPU

In [1]:
!nvidia-smi

Wed Sep 25 20:13:26 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 561.09                 Driver Version: 561.09         CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3070 ...  WDDM  |   00000000:01:00.0  On |                  N/A |
| N/A   43C    P8             14W /  140W |     543MiB /   8192MiB |      7%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
import torch
torch.cuda.is_available()

True

In [6]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [3]:
tensor = torch.tensor([1,2,3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [7]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [8]:
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [9]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])