In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.1+cu118


In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [11]:
vector= torch.tensor([7,7,7,7])
vector

tensor([7, 7, 7, 7])

In [9]:
vector.ndim


1

In [12]:
vector.shape

torch.Size([4])

In [15]:
matrix = torch.tensor([[7,7], [8,1]])
matrix

tensor([[7, 7],
        [8, 1]])

In [16]:
tensor = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [17]:
tensor.ndim

torch.Size([1, 3, 3])

In [18]:
tensor.shape

torch.Size([1, 3, 3])

In [19]:
tensor.ndim

3

In [32]:
tensor = torch.tensor([[[3,2,1],[3,2,1],[32,1,32]],[[123,321,123],[6,4,2],[80,12,20]]])
tensor

tensor([[[  3,   2,   1],
         [  3,   2,   1],
         [ 32,   1,  32]],

        [[123, 321, 123],
         [  6,   4,   2],
         [ 80,  12,  20]]])

In [28]:
tensor.shape

torch.Size([2, 3, 3])

In [29]:
tensor.ndim

3

In [30]:
tensor.size()

torch.Size([2, 3, 3])

In [33]:
tensor.device

device(type='cpu')

In [42]:
#Random tensor
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7637, 0.5889, 0.2309, 0.4452],
        [0.3394, 0.8477, 0.4838, 0.8127],
        [0.7277, 0.7497, 0.3501, 0.4274]])

In [43]:
random_image = torch.rand(size = (224, 224, 3)) #height, width, color channels (rgb)
random_image.shape, random_image.ndim

(torch.Size([224, 224, 3]), 3)

In [45]:
#zero/one tensor
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [48]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [49]:
#range of tensors and tensors-like
torch.range(0,10)

C:\Users\appclan\AppData\Local\Temp\ipykernel_15784\2533155496.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [55]:
one_to_hundred = torch.arange(start=0, end = 100, step= 10)
one_to_hundred

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [57]:
ten_zeros = torch.zeros_like(input=one_to_hundred)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [61]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                                dtype= None, # data type
                                device = None, # which device use tensor
                                requires_grad=False) #track gradients
float_32_tensor

tensor([3., 6., 9.])

In [63]:
float_16_tensor = float_32_tensor.type(torch.float16) # or half
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [67]:
(float_16_tensor * float_32_tensor).dtype
#float_16_tensor.dtype, float_32_tensor.dtype

torch.float32

In [68]:
int_32_tensor = torch.tensor([3,6,9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [69]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

#get info from tensors
1. Tensor datatype = tensor.dtype
2. Tensor shape = tensor.shape
3. Tensor device = tensor.device

In [81]:
some_tensor = torch.rand(3,4,4).type(torch.float16).to(device="cpu")
some_tensor

tensor([[[0.7603, 0.3511, 0.9419, 0.3267],
         [0.2888, 0.1460, 0.4993, 0.3665],
         [0.3579, 0.9170, 0.7866, 0.5684],
         [0.6265, 0.6226, 0.9897, 0.7412]],

        [[0.5093, 0.5029, 0.1106, 0.4507],
         [0.2427, 0.8569, 0.9072, 0.8101],
         [0.6216, 0.0056, 0.2430, 0.0580],
         [0.3762, 0.9370, 0.2131, 0.3564]],

        [[0.1014, 0.5962, 0.7705, 0.2472],
         [0.7910, 0.1838, 0.9233, 0.6128],
         [0.4014, 0.6079, 0.2035, 0.1772],
         [0.7764, 0.5811, 0.1360, 0.5283]]], dtype=torch.float16)

In [82]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[[0.7603, 0.3511, 0.9419, 0.3267],
         [0.2888, 0.1460, 0.4993, 0.3665],
         [0.3579, 0.9170, 0.7866, 0.5684],
         [0.6265, 0.6226, 0.9897, 0.7412]],

        [[0.5093, 0.5029, 0.1106, 0.4507],
         [0.2427, 0.8569, 0.9072, 0.8101],
         [0.6216, 0.0056, 0.2430, 0.0580],
         [0.3762, 0.9370, 0.2131, 0.3564]],

        [[0.1014, 0.5962, 0.7705, 0.2472],
         [0.7910, 0.1838, 0.9233, 0.6128],
         [0.4014, 0.6079, 0.2035, 0.1772],
         [0.7764, 0.5811, 0.1360, 0.5283]]], dtype=torch.float16)
Datatype of tensor: torch.float16
Shape of tensor: torch.Size([3, 4, 4])
Device tensor is on: cpu


### manipulating tensors

* add
* sub
* mult (element-wise)
* div
* mat_mult

In [83]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [84]:
tensor * 10

tensor([10, 20, 30])

In [86]:
tensor - 10

tensor([-9, -8, -7])

In [87]:
#Inbuilt func
torch.mul(tensor,10)

tensor([10, 20, 30])

###matrix mult
1. element-wise mult
2. matrix mult (dot product)

In [88]:
tensor

tensor([1, 2, 3])

In [90]:
print(tensor, "*" ,tensor)
print(f"Equals : {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals : tensor([1, 4, 9])


In [91]:
torch.matmul(tensor,tensor)

tensor(14)

In [99]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 996 μs


In [100]:
%%time
torch.matmul(tensor,tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

### Main rules for matrix_mult:
1. inner dimensions must match:
    * (3,1) @ (1,3)
2. result shape = outer dimensions:
    * (3,1) @ (1,3) = (3,3)


In [101]:
print(torch.rand(3,1) @ torch.rand(1,3))

tensor([[0.1358, 0.2313, 0.1770],
        [0.1615, 0.2750, 0.2105],
        [0.0481, 0.0819, 0.0627]])


### shape error

In [102]:
#shape for mat_mult
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
torch.mm(tensor_A, tensor_B) # mm = mat_mult

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [104]:
#to fix, use on one tensor transpose func
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [106]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [107]:
torch.mm(tensor_A.T, tensor_B)

tensor([[ 76, 103],
        [100, 136]])